name: CI Pipeline

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
          MYSQL_ROOT_PASSWORD: rootpassword
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping --host=127.0.0.1 --user=testuser --password=testpassword --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      - name: Install dependencies
        run: npm install

      - name: Set up Prisma
        run: |
          npx prisma generate
          npx prisma migrate dev --name init

      - name: Run tests
        run: npm test
        env:
          DATABASE_URL: mysql://testuser:testpassword@127.0.0.1:3306/testdb
